### ISSUE TITLE
Questions on state variable & payload

### ISSUE THREAD

**Issue by thorbenandresen** [justinwoo/redux-rx-fun#1]
Hi Justin, 

just came across the repo, which I find super interesting! I am just beginning to learn RxJS so I hope you dont mind a couple of beginner questions: 

**State var**

Where do you pass the state variable to the view function? (rxState)
https://github.com/justinwoo/redux-rx-fun/blob/master/src/rx-app.js#L49

I don't see really how it works here:
https://github.com/justinwoo/redux-rx-fun/blob/master/src/index.js#L17

I tried to replicate this example in my React Native App but I fail to pass a reactive sate var: 
https://gist.github.com/Thorbenandresen/1a87cfdb774736db006e

**Payload**

How would you pass payload to your "reducer" functions (projectIncrement(), projectIDecrement())? 

Thanks

Thorben

**Comment by justinwoo** [comment]
The first one's a little confusing, since I export the function and then initialize it in [`index.js`](https://github.com/justinwoo/redux-rx-fun/blob/fb522f0664b3f7200a6eb09b781e37d0104c4786/src/index.js#L15-L17)

I see you've linked to it already -- in Rx, most everything is a lazy computation, and `subscribe` signals to the observable chain that an observer has attached, and at that point, the "subscription" part makes everything finally run (I think watching the first 12 min of [this talk](https://www.youtube.com/watch?v=QhjALubBQPg) will get you up to speed quickly).

Right, in your code, you are producing the component, but it isn't going anywhere. You'll see that my `renderRxApp` function makes the view **and** renders it to the dom. You might find it convenient to just attach another operator (`map`, probably) to take the react components stream and render them, as subscribers are meant to be effect-ful.

You'll see that my "reducer functions" have this kind of structure: `projectIncrement(e: Any): (state: State) => (state: State)`. Since each of them are mapped functions that produce another structure, you would pass an event object (or really, any data) into the stream and be able to use it.

**Comment by justinwoo** [comment]
Sorry for the mis-submit earlier, I've updated my answer fully. I hope my answer makes some sense.

**Comment by thorbenandresen** [comment]
Hi Justin, thank you very much - I got the example working now incl. payload. This is awesome/powerful stuff!

**Comment by thorbenandresen** [comment]
Hi Justin!

I still can't wrap my head around how I can implement this React Native (my ReactDom example works fine). 

Here is my best try: https://gist.github.com/Thorbenandresen/515442a03ff3b3943e3d

The renders the initial state, but it fails to re-render the state in the view component upon when I modify the state. I know why this happens (state is not a prop, thus no re-render), but I don't know how I can fix this.

![screen shot 2016-02-15 at 6 24 13 pm](https://cloud.githubusercontent.com/assets/8238976/13063737/ec7ea408-d418-11e5-8f6a-5075448e0a25.jpg)

I know this might be out of the scope of this repo, but maybe you can help anyways.

**Comment by justinwoo** [comment]
I don't think I understand what's going on in your render function. You're defining a function for your component each time? `module.exports` is a one time thing that's meant to declare semi-static exports of your module though. `renderRxApp` should actually render the component. You might mean to export an Observable of components that is mapped to `state$` though.
